Tlaster/PreCompose

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
When the NavHost is disposed its back stack manager needs to be unregistered. This should avoid leaks and incorrectly having invalid BackHandlers in the active handlers list.
> Unregister NavHost back stack manager when disposed

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/SwipeProperties.kt
Fix #43 and remove some boilerplate code.
`NavHostContent` was called multiple times to workaround a Compose bug when content is not displayed if it has negative offset. It didn't work well with route lifecycle.
> Fix broken swipe back

- buildSrc/src/main/kotlin/Versions.kt
- precompose/build.gradle.kts
- precompose/src/androidMain/kotlin/moe/tlaster/precompose/lifecycle/PreComposeActivity.kt
Changing ComponentActivity to FragmentActivity(which extends ComponentActivity) for supportFragmentManager access. This is required for BiometricPrompt for biometric login.
> Changing ComponentActivity to FragmentActivity

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/flow/FlowExtensions.kt
- sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/scene/NoteEditScene.kt
Fixed that sometimes the "collectAsStateWithLifecycle" function didn't work immediately (For example, this is very noticeable using with TextField).
Added "collectAsStateWithLifecycle" extension function for StateFlow.
Changed the function "collectAsState" to "collectAsStateWithLifecycle" in the todo sample (NoteEditScene.kt).
> Flow & StateFlow extensions

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
Hi. 
Sorry for missing state preservation in swipe back navigation. Thanks for fixing it.
There is an infinite recompositions bug in your fix.  
P.S. Also there is an issue when swiped entry flashing after it was dismissed ( you can see it on last clip). Reproduces before this fix too.
Before:
https://github.com/Tlaster/PreCompose/assets/63979218/ac5048ae-5629-4951-b74f-b5e033cf3bab
After:
https://github.com/Tlaster/PreCompose/assets/63979218/d1654d0b-a6b3-4102-80e2-89e53f1b51a0
> Fix swipe recompositions

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/ui/BackPressAdapter.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/RouteBuilderTest.kt
Hi, first of all, thanks for working on this.
This PR attempts to fix some issues that I encountered while working with the library:
1. BackHandler doesn't work as expected, and I found two issues here:
**i.** When we register the `backHandler`, we [add](https://github.com/Tlaster/PreCompose/blob/fb65985d99dcacbe9f057df42c061958212f5e43/precompose/src/commonMain/kotlin/moe/tlaster/precompose/ui/BackPressAdapter.kt#L33) it to the top of the list, while when we try to find the handler to use, we use the last one, and this means that the first attached handler will alway be used, instead of using the one from the current screen, I attempted to fix this with the commit 32e93641e004d74ad0bd758baed80e8077169bce
**ii.** The `BackPressAdapter` state (I mean the `canHandleBackPress`) is …
> Fix some issues (check description)

- precompose-viewmodel/src/commonMain/kotlin/moe/tlaster/precompose/viewmodel/ViewModelAdapter.kt
- precompose/src/androidMain/kotlin/moe/tlaster/precompose/lifecycle/PreComposeActivity.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/stateholder/SavedStateHolder.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackEntryTest.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/NavigatorTest.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/SeavableStateRegistry.kt
- sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/App.kt
- sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/scene/NoteEditScene.kt
- sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/viewmodel/NoteEditViewModel.kt
The currently implemented `StateHolder` saves components only during configuration changes, this PR adds an additional component to allow saving some state to be persisted during process-death in Android too, it's done in a similar way to `StateHolder`, the app will have a root `SavedStateHolder`, and each `BackStackEntry` will have its own copy, this allows scoping keys too to avoid the chance of having duplicate keys saved.
The implementation uses `SaveableStateRegistry`, it's quite simple, and it doesn't impact platforms that don't implement it (basically all platforms except Android).
Client apps are responsible of checking whether the component can save the data, and we can even add a way to Parcelize classes in the library to make this easier, but it's outside of the scope of this …
> Add a way to save and restore data to the Saved State

- buildSrc/src/main/kotlin/Versions.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
- precompose/src/macosMain/kotlin/moe/tlaster/precompose/ComposeWindow.kt
- precompose/src/uikitMain/kotlin/moe/tlaster/precompose/PreComposeApplication.kt
- sample/molecule/src/uikitMain/kotlin/moe/tlaster/precompose/molecule/sample/Main.kt
- sample/todo/ios/src/uikitMain/kotlin/main.uikit.kt
This includes updates to the following:
| Library | From | To |
|--------|--------|--------|
| Kotlin | 1.8.2 | 1.9.0 |
| Coroutines | 1.7.1 | 1.7.3 |
| Compose | 1.4.2 | 1.5.0-beta03 |
| Jetbrains Compose | 1.4.0 | 1.5.0-dev1122 | 
| AndroidX Activity | 1.7.0 | 1.7.2 | 
`AnimatedContentScope` was converted to an Interface so now we need to use `AnimatedContentTransitionScope`
`EnterTransition` `with` is deprecated and replaced by `togetherWith`
`ComposeUIViewController` replaces `Application` on iOS and title string parameter is no longer used so removed.
I'm running this in a new project targeting Android, iOS & JVM. My project is running and navigating on each platform. Publish and test gradle commands succeed.
Note:
This is my first time submitting a PR to an OSS project. Please let …
> Compose 1.5.0 beta, Kotlin 1.9.0, minor Coroutines and AndroidX Activity version

- docs/setup.md
- precompose/src/androidMain/kotlin/moe/tlaster/precompose/lifecycle/PreComposeActivity.kt
- sample/molecule/src/androidMain/kotlin/moe/tlaster/precompose/molecule/sample/MainActivity.kt
- sample/todo/android/src/main/java/moe/tlaster/android/MainActivity.kt
Now you don’t need to inherit from PreComposeActivity, you just need to use the setContent function.
In samples, the PreComposeActivity classes have been changed into two variations: ComponentActivity and FragmentActivity.
Maybe you will need to change the file name PreComposeActivity.kt to something else.
Also if this is a good replacement I'll edit the documentation as well.
> Refactor Android PreComposeActivity to ComponentAcitivity extensions

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt
This PR tries to mitigate #134.
Wrapping the `BackStackEntry` in a mutable state will make it `Stable` avoiding triggering recompositions when interacting with it.
> Avoid composing scene multiple times due to BackStackEntry

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt
When performing a screen transition from `Screen A` to the same `Screen A`, with `PopUpTo` with `inclusive` true, `destroyDirectly` will cause a flicker of the screen. 
```kotlin
navigator.navigate(
route = "Screen A",
popUpTo = PopUpTo(
route = "Screen A", 
inclusive = true,
)
)
```
If we change it to `destroy`, it will only destroy the composable only when `Inactive` and it still won't crash as mentioned in 
https://github.com/Tlaster/PreCompose/issues/146.
> Fix flicker on screen transition with PopUpTo with inclusive true.

- sample/molecule/src/commonMain/kotlin/moe/tlaster/precompose/molecule/sample/App.kt
- settings.gradle.kts
The Molecule sample app crashes on desktop and Android:
This PR just wraps contents of `App` in `PreComposeApp` as in the other sample.
> Fix Molecule sample "No StateHolder provided"

- CONTRIBUTING.md
- build.gradle.kts
According to the [CONTRIBUTING.md](/Tlaster/PreCompose/blob/master/CONTRIBUTING.md#development-environment) file, we should have at least the JDK 17 to compile the project.
However, the current setup is pointing to JDK 11, which prevents the project from compiling with JDK 17.
> Update documentation for JDK 11

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt
This allows us to have multiple instances of navigators whenever we need them.
For example, when using multiple NavHosts:
```kotlin
val mainNavigator = rememberNavigator(name = "main")
val homeNavigator = rememberNavigator(name = "home")
NavHost(
navigator = mainNavigator,
initialRoute = "home",
)
NavHost(
navigator = homeNavigator,
initialRoute = "dashboard",
)
```
> Introduce a name to remember Navigator

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt
> add Navigator.previousEntry

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt
- precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt
Having `PopUpTo` as a parameter in the `goBack` function with an `inclusive` flag adds complexity.
Providing multiple values for this operation can lead to confusion.
> Remove confusing API from goBack

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/ComposeRoute.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/FloatingRoute.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/SceneRoute.kt
This scope is the one that drives the navigation transition, which allows callers to use it to drive other animations inside the screen itself as it animates into or out of the NavHost.
Notably, this allows callers to use the shared element transitions.
My only one concern left here is that the `ComposeRoute` interface seems to have been public, even though callers probably had no reason to use the interface in a meaningful way, much less extend it so that this change would be a breaking API change for them. Am I missing something here? Should that change also happen in a backwards compatible way here? Please do let me know if it is the case and I can try and look further into that instead.
Shared more thoughts here https://github.com/Tlaster/PreCompose/issues/308#issuecomment-2062638157
> Make scene provide an AnimatedContentScope to the composable content

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
Changed `NavHost` layout implementation so that `BoxWithConstraints` layout that wraps the `NavHostContent` will be composed only when there's a `BackStackEntry` to display.
There is an issue when the `NavHost` is inside a `ModalBottomSheet`, and the `NavHost` is wrapped by `animateContentSize()` Modifier. It interferes with showing animation of the bottom sheet, where it hangs for an additional ~600ms at the bottom of the screen. It appears that not composing the layout (`BoxWithConstraints`) when there's no `BackStackEntry` solves the issue. 
Issue link: https://github.com/Tlaster/PreCompose/issues/313
Changes:
- Added an `if` statement wrapping `BoxWithConstraints` so that it'll compose only when `currentSceneEntry` or `currentFloatingEntry` is not null.
We could avoid the `if` if not …
> fix animateContentSize NavHost Modifier

- precompose/build.gradle.kts
- sample/molecule/build.gradle.kts
Looks like appcompat is not needed? 
More context in https://github.com/paug/AndroidMakersApp/pull/299
> Remove appcompat dependency

- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
- precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/SwipeProperties.kt
Currently, the swipe back gesture is controlled by `SwipeProperties`, and the gesture space is set by `spaceToSwipe`.
The problem with the current approach is that all touch events within the `spaceToSwipe `space are intercepted. If one needs to enable the full scene swipe (like it's done in Telegram), then none of the elements within the scene will be available for interactaction. 
This pull request introduces a fix for the full scene swipe without intercepting touch events.
The`spaceToSwipe` property has also been removed because it is not compatible with the fix and because the swipe-back gesture usually works across the entire scene.
> Fix the full scene swipe without intercepting touch events

- precompose/src/jsMain/kotlin/moe/tlaster/precompose/PreComposeWindow.kt
- precompose/src/wasmJsMain/kotlin/moe/tlaster/precompose/PreComposeApp.kt
Hi I have found exact the same issue as in #98 but for JS targets.
Lifecycle for JS targets is not initialised with Active state so collect is not not grabbing any events.
I have found this issue when working on JS support for typesfe navigation 
Lavmee/precompose-navigation-typesafe#36
```
val navigator = rememberNavigator()
val currentEntry by navigator.currentEntry.collectAsStateWithLifecycle(null)
```
This PR fixes the issue and moves lifecycle to active state after creation of PreComposeWindowHolder
before
https://github.com/user-attachments/assets/78f50383-29b7-4531-b88f-98e3575b085a
after
https://github.com/user-attachments/assets/028a8b4e-089a-42ce-8fa2-176da0119923
> handle lifecycle in JS targets

- precompose-molecule/build.gradle.kts
- precompose-molecule/src/wasmJsMain/kotlin/moe/tlaster/precompose/molecule/ProvidePlatformDispatcher.kt
- sample/molecule/build.gradle.kts
- sample/molecule/src/wasmJsMain/kotlin/moe/tlaster/precompose/molecule/sample/Main.kt
- sample/molecule/src/wasmJsMain/resources/index.html
- sample/molecule/src/wasmJsMain/resources/styles.css
When imported molecule package I have noticed that it misses wasm support.
This PR:
- adds wasm support for precompose-molecule package
- adds wasm target for molecule sample
https://github.com/user-attachments/assets/cc022461-6997-49c1-966e-77bc0a6bff0e
> added support for molecule for js wasm
