precompose-molecule/build.gradle.kts
precompose-viewmodel/build.gradle.kts
precompose/build.gradle.kts
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/SwipeProperties.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/SceneRoute.kt

Hey again.
UIKIt navigation with compose is too laggy now so i just added iOS-like compose swipe back navigation.

Swipe back navigation

---

precompose/src/androidMain/kotlin/moe/tlaster/precompose/lifecycle/PreComposeActivity.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/UiClosable.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt

fix crash when push back and immediate navigate

---

build.gradle.kts
precompose/build.gradle.kts
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/ComposeRoute.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/FloatingRoute.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/GroupRoute.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/route/SceneRoute.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/RouteBuilderTest.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/TestRoute.kt
precompose/src/jsMain/kotlin/moe/tlaster/precompose/PreComposeWindow.kt

add group navigation support

---

precompose-molecule/src/commonMain/kotlin/moe/tlaster/precompose/molecule/molecule.kt

add immediate clock support for molecule intergration

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/SwipeProperties.kt

Fix for SwipeProperties with rememberSaveable

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/PopUpTo.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt

fix state id generation

---

README.md

Thanks for building PreCompose! ❤️

Fix typo in "JetBrains"

---

docs/component/koin.md

Documentation is out of date

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/QueryString.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/QueryStringTest.kt

Hi, I have a little optimization for QueryString

refactor and optimize QueryString

---

precompose/src/iosMain/kotlin/moe/tlaster/precompose/PreComposeApplication.kt

fix ios notification center crash

---

precompose/src/jvmMain/kotlin/moe/tlaster/precompose/PreComposeWindow.kt

JVM Desktop WindowAdapter on window opened set state to active.

---

precompose/src/jvmMain/kotlin/moe/tlaster/precompose/PreComposeWindow.kt

fix jvm window closing callback

---

precompose-koin/build.gradle.kts
precompose-molecule/build.gradle.kts
precompose-viewmodel/build.gradle.kts

fix library dependencies

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt

Fix and expose canNavigate from BackStackManager

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt

fix crash when using swipe during navigating

---

gradle/libs.versions.toml
sample/todo/android/src/main/AndroidManifest.xml
sample/todo/android/src/main/java/moe/tlaster/android/TodoApplication.kt
sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/App.kt
sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/di/AppModule.kt
sample/todo/desktop/src/jvmMain/kotlin/Main.kt
sample/todo/ios/src/uikitMain/kotlin/Main.uikit.kt
sample/todo/js/src/jsMain/kotlin/Main.kt
sample/todo/macos/src/macosMain/kotlin/Main.kt

Issue : https://github.com/Tlaster/PreCompose/issues/222

Fix crash Koin compose 1.1.2 in Sample todo

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt

fix navigation bug when transition is none

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/lifecycle/LifecycleRegistry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt
precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteGraph.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/BackStackManagerTest.kt
precompose/src/commonTest/kotlin/moe/tlaster/precompose/navigation/NavigatorTest.kt

fix issues when route graph being updated

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt

fix can not observe lifecycle from scene

---

precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt

fix spaceToSwipe

---

precompose/build.gradle.kts

fix test dependency
